name: ton80
version: 0.1.0
description: Ton 80 is a benchmark suite for Dart.
environment:
  sdk: '>=1.2.0'
dependencies:
  browser: '^0.10.0'
  path: '>=1.3.0 <=1.4.2'
  quiver: '>=0.21.0 <0.23.0'
  args: '>=0.13.0 <0.14.0'
dependency_overrides:
  build:
    git:
      url: https://github.com/dart-lang/build
      ref: kernel
      path: build
  build_compilers:
    git:
      url: https://github.com/dart-lang/build
      ref: kernel
      path: build_compilers
  build_runner:
    git:
      url: https://github.com/dart-lang/build
      ref: kernel
      path: build_runner
  build_test:
    git:
      url: https://github.com/dart-lang/build
      ref: kernel
      path: build_test
web:
  compiler:
    debug: dartdevc
